print('\033[94m STUDENT BIO-DATA', end = '\033[0m')
print()
name = input('name: ').strip().capitalize()
email = input('Email: ').strip()
paw = input('paw : ').strip()
Dob = input('Dob : ').strip()
Adress = input('Adress: ').strip()
phone = input('phone number: ')

bio = {'name': name, 'email': email, 'paw': paw, 'Dob': Dob, 'Adress': Adress, 'phone': phone}
print()
print(f""" \033[36m Name: {bio['name']}""")
print()
print(f""" \033[32m Email: {bio['email']}""")
print()
print(f""" \033[35m Password: {bio['paw']}""")
print()
print(f""" \033[31m Date of birth: {bio['Dob']}""")
print()
print(f""" \033[0m  Adress: {bio['Adress']}""")
print()
print(f""" \033[94m Phone number: {bio['phone']}""")
